version: '3.8'

services:
  # ────────────────────────────────
  #  Node.js app (price ingester)
  # ────────────────────────────────
  app:
    build: .
    container_name: crypto-price-app
    depends_on:
      - questdb
    environment:
      QUESTDB_HOST: questdb
      FETCH_INTERVAL_MS: 60000
      TZ: Asia/Tbilisi        # ← container clock in GMT+4
    restart: unless-stopped

  # ────────────────────────────────
  #  QuestDB time-series database
  # ────────────────────────────────
  questdb:
    image: questdb/questdb:latest
    container_name: liquid-questdb
    ports:
      - "9000:9000"           # Web UI  + HTTP ILP
      - "8812:8812"           # PostgreSQL wire protocol
      - "9009:9009"           # TCP ILP
      - "9003:9003"           # Health & metrics
    volumes:
      - ./.questdb:/var/lib/questdb
    environment:
      - TZ=Asia/Tbilisi
      - QDB_PG_READONLY_USER_ENABLED=true
    restart: unless-stopped

  # ────────────────────────────────
  #  Grafana visualisation
  # ────────────────────────────────
  grafana:
    image: grafana/grafana-oss
    container_name: liquid-grafana
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Tbilisi
    depends_on:
      - questdb
    restart: unless-stopped
  caddy:
    image: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    restart: unless-stopped
